#!/usr/bin/env ruby

require 'dotenv'
Dotenv.load('.deploy.env')

require_relative 'stack_creator'

stack_name = ARGV[0]

stack_creator = StackCreator.new(
  region: ENV.fetch('AWS_REGION', nil),
  access_key_id: ENV.fetch('ACCESS_KEY_ID', nil),
  secret_access_key: ENV.fetch('SECRET_ACCESS_KEY', nil),
  account_id: ENV.fetch('AWS_ACCOUNT_ID'),
)

stack_creator.call(
  stack_name,
  {},
)
